// Shared imports for scenes (keeps scene files focused on choreography).
export {useCurrentFrame, Img, staticFile} from 'remotion';
export {Fill, At, Cam, Win, Seg, W, H} from '../components/core';
export {HistoricalImage, Figure} from '../components/HistoricalImage';
export {ParallaxPainting} from '../components/ParallaxPainting';
export {TypographyImpact, StaggerText} from '../components/TypographyImpact';
export {DateCard, Rule, Caption} from '../components/DateCard';
export {BattleTitle} from '../components/BattleTitle';
export {NameMotif} from '../components/NameMotif';
export {FilmGrain, Vignette, Scanlines, CRT, HalftoneOverlay, Tint, Parchment} from '../components/FilmGrain';
export {ChromaticAberration, SliceGlitch} from '../components/ChromaticAberration';
export {FlashFrame, Flashes} from '../components/FlashFrame';
export {CameraShake} from '../components/CameraShake';
export {EagleEmblem, EagleFlyThrough} from '../components/EagleTransition';
export {ParticleField, Smoke, Fog} from '../components/ParticleField';
export {AnimatedMap, AnimatedArrow, MapGlow, MapPing, camAt, lerpCam} from '../components/AnimatedMap';
export type {MapCam, MapLabel} from '../components/AnimatedMap';
export {Montage} from '../components/Montage';
export {IrisReveal, BicorneWipe, whipStyle, crashZoom, ZoomStreaks} from '../components/Transitions';
export {Sunburst, Tunnel, ColorField, StripeField, DotField} from '../components/PsychBG';
export {Eagle} from '../components/art/Eagle';
export {Bicorne, Laurel, Crown, LegionStar, BeeField, NMonogram} from '../components/art/Regalia';
export {CannonBlueprint, CannonSilhouette, InfantryRank, Ship, Flag, CrossedSabres, Sabre} from '../components/art/Military';
export {Pyramids, NotreDame, BrandenburgGate, MoscowSkyline, Island, Guillotine, LongwoodHouse} from '../components/art/Skylines';
export {Doc, Handwriting} from '../components/art/Documents';
export {Memory} from '../components/Memories';
export {MARKERS, b, BEAT, BAR} from '../data/beats';
export {POWER} from '../data/motifs';
export {P, route, PLACES} from '../data/campaigns';
export {F} from '../fonts';
export * from '../utils/animation';
export * from '../utils/easing';
export {accel} from '../utils/timing';
export type {Shot, ShotFn} from '../utils/timing';
